steps:
  - command: |
      mkdir -p bin
      mkdir -p logs/build
      echo 'touch bin/hello' > logs/build/hello.txt
      touch bin/hello
    plugins:
      uw-ipd/rsync#d7c64c0:
        post:
         - "-Rrv bin buildbot@fw.bakerlab.org:~/test_pipeline/${BUILDKITE_BUILD_NUMBER}"
         - "-Rrv logs/*/*.txt buildbot@fw.bakerlab.org:~/test_pipeline/$${BUILDKITE_JOB_ID}"
