steps:
  - command: |
      echo hello > hello_world.txt
    artifact_paths:
      - hello_world.txt
    agents:
      # Upload pipeline into the current agent queue.
      - queue=${PIPELINE_QUEUE:-${BUILDKITE_AGENT_META_DATA_QUEUE}}
